### ISSUE TITLE
lazy einsum

### ISSUE THREAD

**Issue by acycliq** [jcmgray/autoray#19]
Hi!

many thanks for this nice library. I dont understand how to run a lazy einsum please. For example in dask terms that would be:
```
import dask.array as da

x = [[1,2],[3,4]]
de = da.einsum('ij, nk -> ', x, x)
de.compute()
```
I might not get it right, but I believe under autoray this should be:
```
from autoray import lazy

x = [[1,2],[3,4]]
lx = lazy.array(x)
le = np.einsum('ij, nk -> ', lx, lx)
```

and this is where it fails. The error I get on pyCharm is: 
```
/home/dimitris/miniconda3/envs/autoray/lib/python3.9/site-packages/autoray/lazy/core.py:1414: UserWarning: Could not find a full input parser for einsum expressions. Please install either cotengra or opt_einsum for advanced input formats (interleaved, ellipses, no-output).
  warnings.warn(
Traceback (most recent call last):
  File "/home/dimitris/dev/python/pciSeq/run_app.py", line 14, in <module>
    le = lazy.einsum('ij, nk->', lx, lx)
  File "/home/dimitris/miniconda3/envs/autoray/lib/python3.9/site-packages/autoray/lazy/core.py", line 1118, in wrapped
    return fn(*args, **kwargs)
  File "/home/dimitris/miniconda3/envs/autoray/lib/python3.9/site-packages/autoray/lazy/core.py", line 1431, in einsum
    size_dict[char] = max(size_dict.get(char, 1), op_shape[i])
IndexError: tuple index out of range
```

For some strange to me reason, the error is different when I run the same commands in a jupyter notebook:

```
[/home/dimitris/miniconda3/envs/autoray/lib/python3.9/site-packages/autoray/lazy/core.py:774](http://localhost:8888/home/dimitris/miniconda3/envs/autoray/lib/python3.9/site-packages/autoray/lazy/core.py#line=773): UserWarning: Iterating over LazyArray to get the computational graph nodes is deprecated - use `LazyArray.descend()` instead. Eventually `iter(lz)` will iterate over first axis slices.
  warnings.warn(
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[4], line 1
----> 1 le = np.einsum('ij, nk -> ', lx, lx)

File [~/miniconda3/envs/autoray/lib/python3.9/site-packages/numpy/core/einsumfunc.py:1371](http://localhost:8888/home/dimitris/miniconda3/envs/autoray/lib/python3.9/site-packages/numpy/core/einsumfunc.py#line=1370), in einsum(out, optimize, *operands, **kwargs)
   1369     if specified_out:
   1370         kwargs['out'] = out
-> 1371     return c_einsum(*operands, **kwargs)
   1373 # Check the kwargs to avoid a more cryptic error later, without having to
   1374 # repeat default values here
   1375 valid_einsum_kwargs = ['dtype', 'order', 'casting']

ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 32.
```

Am i doing something wrong please? Thanks in advance

**Comment by jcmgray** [comment]
My guess is that currently the space is being interpreted as an index, could you try without it?

**Comment by acycliq** [comment]
Oh I see. i didnt know about autoray.numpy. Both of your points are spot-on. The code below works

```
    x = [[1, 2], [3, 4]]
    lx = lazy.array(x)
    le = autoray.numpy.einsum('ij,nk->', lx, lx)
    print(le.compute())
```

I do get this warning tho:
```
/home/dimitris/miniconda3/envs/autoray/lib/python3.9/site-packages/autoray/lazy/core.py:1414: UserWarning: Could not find a full input parser for einsum expressions. Please install either cotengra or opt_einsum for advanced input formats (interleaved, ellipses, no-output).
  warnings.warn(
```
Is this something I should worry about?

I also tried earlier today to do the `do` syntax but couldnt make it work. And I wasnt sure if it is needed to be honest. If you got time could you tell me how the einsum is supposed to be done with the `do` syntax please?

Thanks so much!

**Comment by jcmgray** [comment]
> Is this something I should worry about?

if you are just supplying the fully specified einsum string then no worries: it’s just for the more advanced einsum syntax features listed.

**Comment by acycliq** [comment]
Thanks a lot for your help!
