### ISSUE TITLE
Cannot do instance check on autoray.numpy and ABC

### ISSUE THREAD

**Issue by williamwen42** [jcmgray/autoray#20]
Found when trying to fix https://github.com/pytorch/pytorch/issues/93624.

Repro:
```python
from abc import ABC
from autoray import numpy as np

class Base(ABC):
    pass

isinstance(np, Base)
```

Error:
```
Traceback (most recent call last):
  File "/data/users/williamwen/pytorch2/playground3.py", line 7, in <module>
    isinstance(np, Base)
  File "/data/users/williamwen/py310-env/lib/python3.10/abc.py", line 119, in __instancecheck__
    return _abc_instancecheck(cls, instance)
  File "/data/users/williamwen/py310-env/lib/python3.10/abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

I got around this by adding
```python
if fn == "__class__":
    return NumpyMimic
```
in the `NumpyMimic` class `__getattribute__`. Perhaps additional cases need to be added as well?

**Comment by jcmgray** [comment]
Thanks for the issue, should be fixed by #21, will merge and mint a release shortly.
