### ISSUE TITLE
np.random.normal with default backend gives error

### ISSUE THREAD

**Issue by fishjojo** [jcmgray/autoray#25]
```
>>> from autoray import numpy as np
>>> x = np.random.normal(size=(6, 6))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xzhang/anaconda3/envs/py311/lib/python3.11/site-packages/autoray/autoray.py", line 79, in do
    backend = _choose_backend(fn, args, kwargs, like=like)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xzhang/anaconda3/envs/py311/lib/python3.11/site-packages/autoray/autoray.py", line 402, in _choose_backend
    return _infer_auto(fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xzhang/anaconda3/envs/py311/lib/python3.11/site-packages/autoray/autoray.py", line 93, in _default_infer_from_sig
    return _DISPATCHERS[fn](*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xzhang/anaconda3/envs/py311/lib/python3.11/site-packages/autoray/autoray.py", line 1390, in default_dispatcher
    return infer_backend(args[0])
                         ~~~~^^^
IndexError: tuple index out of range
```

autoray version: `0.6.12`
python version: `3.11`

**Comment by jcmgray** [comment]
Yes this could be made clearer but is not completely un-intentional: since `autoray` doesn't have a 'default backend' - everything is propagated from the `like` kwarg - and there is nothing to dispatch on, it just errors. You need to specify:

```python
np.random.normal(size=(10, 10), like=like)
```
where `like` is an example array or an explicit string like `"numpy"`.

Possibly favoring `numpy` is what most users expect? `autoray` actually doesn't depend on `numpy` at all though, so I am a bit hesitant to add that. A random number interface is on my to-do list for `autoray`.

**Comment by fishjojo** [comment]
Thanks for the explanation. It's very helpful.
